// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID        string
	RestaurantID   string
	Total          pgtype.Numeric
	RestaurantName string
	OrderDate      pgtype.Timestamptz
	SyncedAt       pgtype.Timestamptz
}
