// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOrder = `-- name: InsertOrder :execrows
INSERT INTO orders (order_id, restaurant_id, restaurant_name, total, order_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (order_id) DO NOTHING
`

type InsertOrderParams struct {
	OrderID        string
	RestaurantID   string
	RestaurantName string
	Total          pgtype.Numeric
	OrderDate      pgtype.Timestamptz
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertOrder,
		arg.OrderID,
		arg.RestaurantID,
		arg.RestaurantName,
		arg.Total,
		arg.OrderDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
