// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existingMessageIDs = `-- name: ExistingMessageIDs :many
SELECT message_id FROM orders
`

func (q *Queries) ExistingMessageIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, existingMessageIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message_id string
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders (message_id, partner, store, total, order_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (message_id) DO NOTHING
`

type InsertOrderParams struct {
	MessageID string
	Partner   string
	Store     string
	Total     pgtype.Numeric
	OrderDate pgtype.Timestamptz
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.MessageID,
		arg.Partner,
		arg.Store,
		arg.Total,
		arg.OrderDate,
	)
	return err
}

const sumLastNDays = `-- name: SumLastNDays :one
SELECT COALESCE(SUM(total), 0)::float8 AS total
FROM orders
WHERE order_date >= now() - make_interval(days => $1::int)
`

func (q *Queries) SumLastNDays(ctx context.Context, days int32) (float64, error) {
	row := q.db.QueryRow(ctx, sumLastNDays, days)
	var total float64
	err := row.Scan(&total)
	return total, err
}
